(define (main)
    (display (+ 5 6))
    (newline)
    (display (number? 5) )
    (newline)
    (display (list? 9) )
    (newline)
    (display (zero? 0) )
    (newline)
    (display (null? 3) )
    (newline)
    (display (string? 2) )
    (newline)
    )

(main)
