(define (main)
  (cond (123 "test"))
  (display (cdr '(modulo)))
  (newline)
  (display (cons '- ''/))
  (newline)
  (display (and (or (not (cond (else "123"))))))
  (newline)
  )

(define (funct2)
  (display '(* round =))
  (newline)
  )

(main)
(funct2)
